
server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:orders
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  application:
    name: ORDER-SERVICE
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: orders_1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  #  config:
  #    import: configserver:http://localhost:9296
  h2:
    console:
      enabled: true
  security:
    user:
      name: root
      password: root

auto:
  create:
    topics:
      enable: true

topic:
  name:
    producer: order-created

